default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PSQL_USERNAME"] || 'postgres' %>
  password: <%= ENV["PSQL_PASSWORD"] || 'postgres' %>
  host: <%= ENV["PSQL_HOST"] || 'localhost' %>

development:
  <<: *default
  database: monterail_development

test:
  <<: *default
  database: monterail_test

production:
  <<: *default
  database: monterail_production
